all: cmd/client/client cmd/server/server

.PHONY: cmd/client/client
cmd/client/client:
	cd cmd/client; go build -o client

.PHONY: cmd/server/server
cmd/server/server:
	cd cmd/server; go build -o server
